apiVersion: v1
kind: Service
metadata:
  name: primeiropay-preauth-service
spec:
  selector:
    app: primeiropay-preauth
    tier: backend
  type: NodePort
  ports:
    - port: 12080
      targetPort: 12080
      protocol: TCP
      nodePort: 30105
