version: '3'

services:
  pre-auth:
    image: douglasdb/pre-auth-svc:latest
    ports:
    - 12088:12088
    environment:
      - preAuthUrl=https://test.oppwa.com/v1/payments
      - entityId=8ac7a4ca6db97ef1016dbe9214e70aac
      - authentication=OGFjN2E0Y2E2ZGI5N2VmMTAxNmRiZTkwZTMxZDBhYTh8WENkRUs0NHJubQ==
